import {
  Mail,
  Home,
  Monitor,
  Users,
  PieChart,
  Video,
  Edit,
  Edit3,
  ExternalLink,
  Tag,
  Command,
  Star,
  BarChart,
  MessageSquare,
  MessageCircle,
  ThumbsUp,
  Instagram,
  Phone,
  Cpu,
  Layers,
  Heart,
  BookOpen,
  AlignCenter,
  AlignLeft,
  Settings,
  Columns,
  Repeat,
  PlusCircle,
  PlusSquare,
  Server,
  Tv,
} from "react-feather";

export default [
  {
    id: "dashboard",
    title: "Dashboard",
    icon: <PieChart size={20} />,
    navLink: "/home",
  },
  {
    id: "wallboard",
    title: "Wallboard",
    icon: <Monitor size={20} />,
    navLink: "/wallboard",
  },
  {
    id: "contacts",
    title: "Contacts",
    icon: <Users size={20} />,
    navLink: "/contacts",
  },
  {
    id: "companies",
    title: "Companies",
    icon: <Home size={20} />,
    navLink: "/companies",
  },
  {
    id: "tickets",
    title: "Tickets",
    icon: <Edit3 size={20} />,
    children: [
      {
        id: "reopentickets",
        title: "Reopen Tickets",
        icon: <Edit size={12} />,
        navLink: "/reopentickets",
      },
      {
        id: "unresolvedtickets",
        title: "Unresolved Tickets",
        icon: <ExternalLink size={12} />,
        navLink: "/unresolvedtickets",
      },
      {
        id: "opentickets",
        title: "Open Tickets",
        icon: <Tag size={12} />,
        navLink: "/opentickets",
      },
      {
        id: "resolved Tickets",
        title: "resolved Tickets",
        icon: <Tag size={12} />,
        navLink: "/resolvedtickets",
      },
    ],
  },
  {
    id: "conversations",
    title: "Conversations",
    icon: <Command size={20} />,
    navLink: "/conversations",
  },
  {
    id: "survey",
    title: "Survey",
    icon: <Star size={20} />,
    navLink: "/survey",
  },
  {
    id: "reports",
    title: "Reports",
    icon: <BarChart size={20} />,
    children: [
      {
        id: "conversations",
        title: "Conversations",
        icon: <Command size={12} />,
        children: [
          {
            id: "livesupport",
            title: "Live Support",
            icon: <MessageSquare size={12} />,
            navLink: "/reports/conversations/livesupports",
          },
          {
            id: "whatsapp",
            title: "Whatsapp",
            icon: <MessageCircle size={12} />,
            navLink: "/reports/conversations/whatsapp",
          },
          {
            id: "facebook",
            title: "Facebook",
            icon: <ThumbsUp size={12} />,
            navLink: "/reports/conversations/facebook",
          },
          {
            id: "instagram",
            title: "Instagram",
            icon: <Instagram size={12} />,
            navLink: "/reports/conversations/instagram",
          },
          {
            id: "telephone",
            title: "Telephone",
            icon: <Phone size={12} />,
            navLink: "/reports/conversations/phone",
          },
          {
            id: "email",
            title: "E-mail",
            icon: <Mail size={12} />,
            navLink: "/reports/conversations/mail",
          },
          {
            id: "videocall",
            title: "Video Call",
            icon: <Video size={12} />,
            navLink: "/reports/conversations/video",
          },
        ],
      },
      {
        id: "ticketreports",
        title: "Ticket Reports",
        icon: <Tag size={12} />,
        children: [
          {
            id: "userreports",
            title: "User Reports",
            icon: <Users size={12} />,
            navLink: "/reports/ticketreports/userreports",
          },
          {
            id: "sourcereports",
            title: "Source Reports",
            icon: <Cpu size={12} />,
            navLink: "/reports/ticketreports/sourcereports",
          },
          {
            id: "statusreports",
            title: "Status Reports",
            icon: <Layers size={12} />,
            navLink: "/reports/ticketreports/statusreports",
          },
        ],
      },
      {
        id: "cxreports",
        title: "Cx Reports",
        icon: <Heart size={12} />,
        navLink: "/reports/cxreports",
      },
    ],
  },
  {
    id: "knowledgebase",
    title: "Knowledge Base",
    icon: <BookOpen size={20} />,
    children: [
      {
        id: "articles",
        title: "Articles",
        icon: <AlignCenter size={12} />,
        navLink: "/knowledgebase/articles",
      },
      {
        id: "categories",
        title: "Categories",
        icon: <AlignLeft size={12} />,
        navLink: "/knowledgebase/categories",
      },
    ],
  },
  {
    id: "settings",
    title: "Settings",
    icon: <Settings size={20} />,
    children: [
      {
        id: "emailtemplates",
        title: "Email Templates",
        icon: <Columns size={12} />,
        navLink: "/settings/emailtemplates",
      },
      {
        id: "smstemplates",
        title: "Sms Templates",
        icon: <MessageSquare size={12} />,
        navLink: "/settings/smstemplates",
      },
      {
        id: "readyanswer",
        title: "Ready Answer",
        icon: <Repeat size={12} />,
        navLink: "/settings/readyanswers",
      },
      {
        id: "conversationreasons",
        title: "Conversation Reasons",
        icon: <PlusCircle size={12} />,
        navLink: "/settings/conversationsreasons",
      },
      {
        id: "ticketreasons",
        title: "Ticket Reasons",
        icon: <PlusSquare size={12} />,
        navLink: "/settings/ticketreasons",
      },
      {
        id: "users",
        title: "Users",
        icon: <Users size={12} />,
        navLink: "/settings/users",
      },
      {
        id: "usergroups",
        title: "User Groups",
        icon: <Server size={12} />,
        navLink: "/settings/usergroups",
      },
      {
        id: "plansandbillings",
        title: "Plans And Billings",
        icon: <Server size={12} />,
        navLink: "/settings/plansandbillings",
      },
      {
        id: "security",
        title: "Security",
        icon: <Server size={12} />,
        navLink: "/settings/security",
      },
      {
        id: "ticketcategories",
        title: "Ticket Categories",
        icon: <Server size={12} />,
        navLink: "/settings/ticketcategories",
      },
      {
        id: "tagmanagement",
        title: "Tag Management",
        icon: <Server size={12} />,
        navLink: "/settings/tagmanagement",
      },
      {
        id: "localization",
        title: "Localization",
        icon: <Server size={12} />,
        navLink: "/settings/localization",
      },
      {
        id: "importdata",
        title: "Import Data",
        icon: <Server size={12} />,
        navLink: "/settings/importdata",
      },
      {
        id: "integrations",
        title: "Integrations",
        icon: <Server size={12} />,
        navLink: "/settings/integrations",
      },
      {
        id: "Role Management",
        title: "Role Management",
        icon: <Server size={12} />,
        navLink: "/role/list",
      },
      {
        id: "Source Management",
        title: "Source Management",
        icon: <Server size={12} />,
        navLink: "/projects/list",
      },
      {
        id: "Auto Assign",
        title: "Auto Assign",
        icon: <Server size={12} />,
        navLink: "/auto-assign/list",
      },
      {
        id: "Call List",
        title: "Call List",
        icon: <Server size={12} />,
        navLink: "/call/list",
      },
    ],
  },
  {
    id: "media",
    title: "media",
    icon: <Tv size={20} />,
    navLink: "/media",
  },
];
